routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\HospitalController;
use App\Http\Controllers\PatientController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('hospital.index');
});

Route::middleware(['auth'])->group(function () {
    Route::resource('hospital', HospitalController::class)->except(['show']);
    Route::resource('patient', PatientController::class)->except(['show']);
});
Route::prefix('auth')->name('auth.')->middleware(['guest'])->group(function () {
    Route::get('/login', [AuthController::class, 'login'])->name('login');
    Route::post('/attempt', [AuthController::class, 'attempt'])->name('attempt');
});
Route::get('auth/logout', [AuthController::class, 'logout'])->name('auth.logout');

app/Models/Patient.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Patient extends Model
{
    use HasFactory;

    protected $guarded = [];
    protected $appends = ['action'];

    public function hospital()
    {
        return $this->belongsTo(Hospital::class);
    }
    public function getActionAttribute()
    {
        return [
            'delete' => route('patient.destroy', ['patient' => $this->attributes['id']]),
            'edit' =>  route('patient.edit', ['patient' => $this->attributes['id']])
        ];
    }
}

app/Http/Controllers/PatientController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PatientRequest;
use App\Libs\Res;
use App\Models\Hospital;
use App\Models\Patient;
use Illuminate\Http\Request;

class PatientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $patients = Patient::with('hospital');
            if ($request->get('hospital')) $patients = $patients->where('hospital_id');
            return Res::success($patients->get());
        }
        return view('patient.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $hospitals = Hospital::get();
        return view('patient.create', compact('hospitals'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PatientRequest $request)
    {
        Patient::create($request->only('hospital_id', 'name', 'address', 'phone_number'));

        return redirect()->route('patient.index')->with('success', 'Pasien berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Patient $patient)
    {
        $hospitals = Hospital::get();
        return view('patient.edit', compact('patient', 'hospitals'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PatientRequest $request, $id)
    {
        Patient::findOrFail($id);
        Patient::whereId($id)->update($request->only('hospital_id', 'name', 'address', 'phone_number'));

        return redirect()->route('patient.index')->with('success', 'Pasien berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $hospital = Patient::whereId($id)->first();
        if (!$hospital) return Res::fail('Pasien tidak ditemukan');
        try {
            Patient::destroy($id);
            return Res::success($hospital, 'Berhasil menghapus pasien');
        } catch (\Throwable $th) {
            return Res::fail($th->getMessage());
        }
    }
}

resources/views/patient/create.blade.php
@extends('layout.main')
@section('content')

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Tambah Pasien</h6>
            </div>
            <div class="card-body">
                <form action="{{route('patient.store')}}" method="POST" class="row">
                    @csrf
                    <div class="col-4">
                        <div class="form-group">
                            <label for="name">Nama Pasien</label>
                            <input type="text" class="form-control" id="name" name="name" value="{{old('name') ?? ''}}">
                            @error('name')
                            <small class="text-danger">{{$message}}</small>
                            @enderror
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="form-group">
                            <label for="phone_number">No Telepon</label>
                            <input type="phone_number" class="form-control" id="phone_number" name="phone_number" value="{{old('phone_number') ?? ''}}">
                            @error('phone_number')
                            <small class="text-danger">{{$message}}</small>
                            @enderror
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="form-group">
                            <label for="phone_number">Rumah Sakit</label>
                            <select class="form-control" name="hospital_id">
                                <option selected disabled>Pilih Rumah Sakit</option>
                                @foreach ($hospitals as $hospital)
                                <option value="{{$hospital->id}}" {{old('hospital_id') == $hospital->id ? 'selected' : ''}}>{{$hospital->name}}</option>
                                @endforeach
                            </select>
                            @error('hospital_id')
                            <small class="text-danger">{{$message}}</small>
                            @enderror
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="form-group">
                            <label for="address">Alamat</label>
                            <textarea name="address" id="address" class="form-control" rows="3">{{old('address') ?? ''}}</textarea>
                            @error('address')
                            <small class="text-danger">{{$message}}</small>
                            @enderror
                        </div>
                    </div>
                    <div class="col-12">
                        <hr>
                        <button class="btn btn-primary">Simpan</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

@section('script')
    @if (session()->has('failed'))
    <script>
        Swal.fire({
        icon: "error",
        title: "{{session()->get('failed')}}",
        showConfirmButton: false,
        timer: 1500,
        });
    </script>
    @endif
    @if (session()->has('success'))
    <script>
        Swal.fire({
        icon: "success",
        title: "{{session()->get('success')}}",
        showConfirmButton: false,
        timer: 1500,
        });
    </script>
    @endif
@endsection

resources/views/patient/edit.blade.php
@extends('layout.main')
@section('content')

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Tambah Pasien</h6>
            </div>
            <div class="card-body">
                <form action="{{route('patient.update',['patient' => $patient->id])}}" method="POST" class="row">
                    @csrf
                    @method('put')
                    <div class="col-4">
                        <div class="form-group">
                            <label for="name">Nama Pasien</label>
                            <input type="text" class="form-control" id="name" name="name" value="{{old('name') ?? $patient->name}}">
                            @error('name')
                            <small class="text-danger">{{$message}}</small>
                            @enderror
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="form-group">
                            <label for="phone_number">No Telepon</label>
                            <input type="phone_number" class="form-control" id="phone_number" name="phone_number"
                                value="{{old('phone_number') ?? $patient->phone_number}}">
                            @error('phone_number')
                            <small class="text-danger">{{$message}}</small>
                            @enderror
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="form-group">
                            <label for="phone_number">Rumah Sakit</label>
                            <select class="form-control" name="hospital_id">
                                <option selected disabled>Pilih Rumah Sakit</option>
                                @php
                                    $hospitalId = old('hospital_id') ?? $patient->hospital_id;
                                @endphp
                                @foreach ($hospitals as $hospital)
                                <option value="{{$hospital->id}}" {{$hospitalId == $hospital->id ? 'selected' :
                                    ''}}>{{$hospital->name}}</option>
                                @endforeach
                            </select>
                            @error('hospital_id')
                            <small class="text-danger">{{$message}}</small>
                            @enderror
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="form-group">
                            <label for="address">Alamat</label>
                            <textarea name="address" id="address" class="form-control"
                                rows="3">{{old('address') ?? $patient->address}}</textarea>
                            @error('address')
                            <small class="text-danger">{{$message}}</small>
                            @enderror
                        </div>
                    </div>
                    <div class="col-12">
                        <hr>
                        <button class="btn btn-primary">Simpan</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

@section('script')
@if (session()->has('failed'))
<script>
    Swal.fire({
        icon: "error",
        title: "{{session()->get('failed')}}",
        showConfirmButton: false,
        timer: 1500,
        });
</script>
@endif
@if (session()->has('success'))
<script>
    Swal.fire({
        icon: "success",
        title: "{{session()->get('success')}}",
        showConfirmButton: false,
        timer: 1500,
        });
</script>
@endif
@endsection

resources/views/patient/index.blade.php
@extends('layout.main')

@section('meta')
<meta name="route-patient" content="{{route('patient.index')}}">
@endsection

@section('content')
<x-table-title title="Pasien" create="{{route('patient.create')}}"></x-table-title>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Daftar Pasien</h6>
            </div>
            <div class="card-body">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama Pasien</th>
                            <th>Alamat</th>
                            <th>No Telepon</th>
                            <th>Rumah Sakit</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


@endsection

@section('script')
<script src="{{asset('js/patient.js')}}"></script>
@if (session()->has('failed'))
<script>
    Swal.fire({
        icon: "error",
        title: "{{session()->get('failed')}}",
        showConfirmButton: false,
        timer: 1500,
        });
</script>
@endif
@if (session()->has('success'))
<script>
    Swal.fire({
        icon: "success",
        title: "{{session()->get('success')}}",
        showConfirmButton: false,
        timer: 1500,
        });
</script>
@endif
@endsection