routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\HospitalController;
use App\Http\Controllers\PatientController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('hospital.index');
});

Route::middleware(['auth'])->group(function () {
    Route::resource('hospital', HospitalController::class)->except(['show']);
    Route::resource('patient', PatientController::class)->except(['show']);
});
Route::prefix('auth')->name('auth.')->middleware(['guest'])->group(function () {
    Route::get('/login', [AuthController::class, 'login'])->name('login');
    Route::post('/attempt', [AuthController::class, 'attempt'])->name('attempt');
});
Route::get('auth/logout', [AuthController::class, 'logout'])->name('auth.logout');

app/Models/Hospital.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Hospital extends Model
{
    use HasFactory;

    protected $guarded = [];
}

app/Http/Controllers/HospitalController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\HospitalRequest;
use App\Libs\Res;
use App\Models\Hospital;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class HospitalController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $hospitals = Hospital::all();
        return view('hospital.index', compact('hospitals'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('hospital.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(HospitalRequest $request)
    {
        try {
            DB::beginTransaction();
            $hospital = Hospital::create($request->only('name', 'address', 'email', 'phone_number'));
            DB::commit();
            return redirect()->route('hospital.index')->with('success', 'Rumah sakit berhasil ditambahkan');
        } catch (\Throwable $th) {
            DB::rollback();
            return redirect()->back()->with('failed', $th->getMessage())->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Hospital $hospital)
    {
        return view('hospital.edit', compact('hospital'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(HospitalRequest $request, $id)
    {
        try {
            DB::beginTransaction();
            $hospital = Hospital::findOrFail($id);
            Hospital::whereId($id)->update($request->only('name', 'address', 'email', 'phone_number'));
            DB::commit();
            return redirect()->route('hospital.index')->with('success', 'Rumah sakit berhasil diubah');
        } catch (\Throwable $th) {
            DB::rollback();
            return redirect()->back()->with('failed', $th->getMessage())->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $hospital = Hospital::whereId($id)->first();
        if (!$hospital) return Res::fail('Rumah Sakit tidak ditemukan');
        try {
            Hospital::destroy($id);
            return Res::success($hospital, 'Berhasil menghapus rumah sakit');
        } catch (\Throwable $th) {
            return Res::fail($th->getMessage());
        }
    }
}

resources/views/hospital/create.blade.php
@extends('layout.main')
@section('content')

<div class="row">
    <div class="col-12">
        @if (session()->has('failed'))
        <div class="alert alert-danger my-4">
            {{session()->get('failed')}}
        </div>
        @endif
        <div class="card">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Tambah Rumah Sakit</h6>
            </div>
            <div class="card-body">
                <form action="{{route('hospital.store')}}" method="POST" class="row">
                    @csrf
                    <div class="col-4">
                        <div class="form-group">
                            <label for="name">Nama Rumah Sakit</label>
                            <input type="text" class="form-control" id="name" name="name" value="{{old('name') ?? ''}}">
                            @error('name')
                            <small class="text-danger">{{$message}}</small>
                            @enderror
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" id="email" name="email" value="{{old('email') ?? ''}}">
                            @error('email')
                            <small class="text-danger">{{$message}}</small>
                            @enderror
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="form-group">
                            <label for="phone_number">Telepon</label>
                            <input type="phone_number" class="form-control" id="phone_number" name="phone_number" value="{{old('phone_number') ?? ''}}">
                            @error('phone_number')
                            <small class="text-danger">{{$message}}</small>
                            @enderror
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="form-group">
                            <label for="address">Alamat</label>
                            <textarea name="address" id="address" class="form-control" rows="3">{{old('address') ?? ''}}</textarea>
                            @error('address')
                            <small class="text-danger">{{$message}}</small>
                            @enderror
                        </div>
                    </div>
                    <div class="col-12">
                        <hr>
                        <button class="btn btn-primary">Simpan</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/hospital/edit.blade.php
@extends('layout.main')
@section('content')

<div class="row">
    <div class="col-12">
        @if (session()->has('failed'))
        <div class="alert alert-danger my-4">
            {{session()->get('failed')}}
        </div>
        @endif
        <div class="card">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Ubah Rumah Sakit</h6>
            </div>
            <div class="card-body">
                <form action="{{route('hospital.update',['hospital' => $hospital->id])}}" method="POST" class="row">
                    @csrf
                    @method('put')
                    <div class="col-4">
                        <div class="form-group">
                            <label for="name">Nama Rumah Sakit</label>
                            <input type="text" class="form-control" id="name" name="name" value="{{old('name') ?? $hospital->name}}">
                            @error('name')
                            <small class="text-danger">{{$message}}</small>
                            @enderror
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" id="email" name="email"
                                value="{{old('email') ?? $hospital->email}}">
                            @error('email')
                            <small class="text-danger">{{$message}}</small>
                            @enderror
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="form-group">
                            <label for="phone_number">Telepon</label>
                            <input type="phone_number" class="form-control" id="phone_number" name="phone_number"
                                value="{{old('phone_number') ?? $hospital->phone_number}}">
                            @error('phone_number')
                            <small class="text-danger">{{$message}}</small>
                            @enderror
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="form-group">
                            <label for="address">Alamat</label>
                            <textarea name="address" id="address" class="form-control"
                                rows="3">{{old('address') ?? $hospital->address}}</textarea>
                            @error('address')
                            <small class="text-danger">{{$message}}</small>
                            @enderror
                        </div>
                    </div>
                    <div class="col-12">
                        <hr>
                        <button class="btn btn-primary">Simpan</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/hospital/index.blade.php
@extends('layout.main')

@section('content')
<x-table-title title="Rumah Sakit" create="{{route('hospital.create')}}"></x-table-title>

<div class="row">
    <div class="col-12">
        {{-- <div class="alert-container">
            @if (session()->has('failed'))
            <div class="alert alert-danger mt-4">
                {{session()->get('failed')}}
            </div>
            @endif
            @if (session()->has('success'))
            <div class="alert alert-success mt-4">
                {{session()->get('success')}}
            </div>
            @endif
        </div> --}}
        <div class="card">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Daftar Rumah Sakit</h6>
            </div>
            <div class="card-body">
                <table class="table table-bordered">
                    <tr>
                        <th>No</th>
                        <th>Nama Rumah Sakit</th>
                        <th>Alamat</th>
                        <th>Email</th>
                        <th>Telepon</th>
                        <th>Aksi</th>
                    </tr>
                    @foreach ($hospitals as $h => $hospital)
                    <tr>
                        <td>{{$h+1}}</td>
                        <td>{{ $hospital->name }}</td>
                        <td>{{ $hospital->address }}</td>
                        <td>{{ $hospital->email }}</td>
                        <td>{{ $hospital->phone_number }}</td>
                        <td>
                            <x-action-button delete="{{route('hospital.destroy',['hospital' => $hospital->id])}}" edit="{{route('hospital.edit',['hospital' => $hospital->id])}}" ></x-action-button>
                        </td>
                    </tr>
                    @endforeach
                </table>
            </div>
        </div>
    </div>
</div>


@endsection

@section('script')
<script src="{{asset('js/hospital.js')}}"></script>
@if (session()->has('failed'))
<script>
    Swal.fire({
        icon: "error",
        title: "{{session()->get('failed')}}",
        showConfirmButton: false,
        timer: 1500,
        });
</script>
@endif
@if (session()->has('success'))
<script>
    Swal.fire({
        icon: "success",
        title: "{{session()->get('success')}}",
        showConfirmButton: false,
        timer: 1500,
        });
</script>
@endif
@endsection